### ISSUE TITLE
include the time needed to walk to the station

### ISSUE THREAD

**Issue by derhuerst** [derhuerst/vbb-anybar#1]
Another argument, e.g. `walking-time`, for the `init` command would be necessary. When fetching departures & computing the indicator color, it should respect this time.

**Comment by CLUBMATEjka** [comment]
Im looking into it...

**Comment by joeinnes** [comment]
Working on it

**Comment by derhuerst** [comment]
Released as `vbb-anybar@0.3.0`, thanks!
